kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cassandra-pvc
  labels:
    app: cassandra
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
