apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
     app: cassandra
  template:
    spec:
      nodeSelector:
        app: cassandra
        version: v1
    metadata:
      labels:
        app: cassandra
        version: v1
    spec:
      containers:
        - name: cassandra
          image: gcr.io/google-samples/cassandra:v13
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "2Gi" # Defina a quantidade desejada de memória (por exemplo, 2 gigabytes)
              cpu: "2000m" # Defina a quantidade desejada de CPU (por exemplo, 1 vCPU)
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          env:
            - name: MAX_HEAP_SIZE
              value: 256M
            - name: CASSANDRA_SEEDS
              value: "cassandra-0.cassandra.sfi2-uc1.svc.ccomv4, cassandra-1.cassandra.sfi2-uc1.svc.ccomv4"
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_START_RPC
              value: "true"
            - name: RPC_ADDRESS
              value: "0.0.0.0"
            - name: CASSANDRA_CLUSTER_NAME
              value: "Cassandra"
            - name: CASSANDRA_NUM_TOKENS
              value: "32"
            - name: CASSANDRA_DC
              value: "DC1"
            - name: CASSANDRA_RACK
              value: "Rack1"
          volumeMounts:
          - name: cassandra-data
            mountPath: /cassandra_data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - whx-rn
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi
